branch-defaults:
  default:
    environment: kkkkkkkk
  master:
    environment: kkkkkkkk
environment-defaults:
  kkkkkkkk:
    branch: null
    repository: null
global:
  application_name: test-application-efja123
  default_ec2_keyname: null
  default_platform: Go 1 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
